<?php 
?>
<!DOCTYPE HTML>
<?php 
include('../escher.html');
?>
<html lang="de-DE">
<head>
  <meta charset="UTF-8">
  <title>Titel der Seite</title>
  <link rel="stylesheet" href="inc/css/style.css" type="text/css" />
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <script type="text/javascript" src="inc/js/script.js"></script>
</head>
<body>
<?php 
include('nav.phtml') 
?>
<div class="page-wrap">
