<?php 
?>
<!DOCTYPE HTML>
<?php 
include('../escher.html');
?>
<html lang="de-DE">
<head>
  <meta charset="UTF-8">
  <title>Hitchtool</title>
  <link rel="stylesheet" href="inc/css/style.css" type="text/css" />
  <meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0;">
  <script type="text/javascript" src="inc/js/jquery-1.8.0.min.js"></script>
  <script type="text/javascript" src="inc/js/script.js"></script>
</head>
<body id="page_<?php echo($site_name) ?>">
<?php 
include('nav.phtml') 
?>
<div class="page-wrap">
